apiVersion: v1
kind: Service
metadata:
  name: {{ include "trade.fullname" . }}-{{ .Values.selenium.hub.serviceName }}
spec:
  selector:
    app: {{ include "trade.fullname" . }}
    component: selenium-hub
  ports:
    - name: http
      port: {{ .Values.selenium.hub.service.port }}
      targetPort: 4444
    - name: event-pub
      port: 4442
      targetPort: 4442
    - name: event-sub
      port: 4443
      targetPort: 4443
  env:
    - name: VNC_PASSWORD
      value: {{ .Values.selenium.hub.service.env.VNC_PASSWORD }}
