{{- if .Values.scrapers.ivscraper.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trade.fullname" . }}-ivscraper
  labels:
    {{- include "trade.labels" . | nindent 4 }}
    component: ivscraper
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "trade.selectorLabels" . | nindent 6 }}
      component: ivscraper
  template:
    metadata:
      labels:
        {{- include "trade.selectorLabels" . | nindent 8 }}
        component: ivscraper
    spec:
      initContainers:
      - name: wait-for-rabbitmq
        image: busybox:1.35
        command: ['sh', '-c']
        args:
          - |
            until nc -z {{ include "trade.fullname" . }}-rabbitmq 5672; do
              echo "Waiting for RabbitMQ..."
              sleep 5
            done
            echo "RabbitMQ is ready!"
      containers:
      - name: ivscraper
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.scrapers.ivscraper.image.repository }}:{{ .Values.scrapers.ivscraper.image.tag }}"
        imagePullPolicy: {{ .Values.scrapers.ivscraper.image.pullPolicy }}
        command: ["sh", "-c"]
        args:
          - |
            Xvfb :99 -screen 0 1280x1024x24 -nolisten tcp &
            export DISPLAY=:99
            python -m news_scraper.scraper_investing
        env:
          - name: DISPLAY
            value: ":99"
          - name: RABBITMQ_URL
            value: {{ include "trade.rabbitmqUrl" . | quote }}
          - name: RABBITMQ_USER
            value: {{ .Values.global.rabbitmqUser | quote }}
          - name: RABBITMQ_PASS
            value: {{ .Values.global.rabbitmqPass | quote }}
        volumeMounts:
          {{- if .Values.persistence.output.enabled }}
          - name: output-volume
            mountPath: /app/output
          {{- end }}
        resources:
          {{- toYaml .Values.scrapers.ivscraper.resources | nindent 10 }}
      {{- if .Values.persistence.output.enabled }}
      volumes:
      - name: output-volume
        persistentVolumeClaim:
          claimName: {{ include "trade.fullname" . }}-output-pvc
      {{- end }}
{{- end }}