{{- if .Values.scrapers.ivscraper.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trade.fullname" . }}-ivscraper
  labels:
    {{- include "trade.labels" . | nindent 4 }}
    component: ivscraper
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "trade.selectorLabels" . | nindent 6 }}
      component: ivscraper
  template:
    metadata:
      labels:
        {{- include "trade.selectorLabels" . | nindent 8 }}
        component: ivscraper
    spec:
      initContainers:
      - name: wait-for-rabbitmq
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          until nc -z {{ include "trade.fullname" . }}-rabbitmq 5672; do
            echo "Waiting for RabbitMQ..."
            sleep 5
          done
          echo "RabbitMQ is ready!"
      containers:
      - name: xvfb
        image: alpine:latest
        command: ['sh', '-c']
        args:
        - |
          apk add --no-cache xvfb
          Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset
        env:
        - name: DISPLAY
          value: {{ .Values.scrapers.ivscraper.env.DISPLAY | quote }}
      - name: ivscraper
        image: "{{ .Values.scrapers.ivscraper.image.repository }}:{{ .Values.scrapers.ivscraper.image.tag }}"
        imagePullPolicy: {{ .Values.scrapers.ivscraper.image.pullPolicy }}
        env:
        - name: DISPLAY
          value: {{ .Values.scrapers.ivscraper.env.DISPLAY | quote }}
        - name: RABBITMQ_URL
          value: {{ include "trade.rabbitmqUrl" . | quote }}
        volumeMounts:
        {{- if .Values.persistence.output.enabled }}
        - name: output-volume
          mountPath: /app/output
        {{- end }}
        resources:
          {{- toYaml .Values.scrapers.ivscraper.resources | nindent 10 }}
      volumes:
      {{- if .Values.persistence.output.enabled }}
      - name: output-volume
        persistentVolumeClaim:
          claimName: {{ include "trade.fullname" . }}-output-pvc
      {{- end }}
{{- end }}
