{{- if .Values.scrapers.tvscraper.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trade.fullname" . }}-tvscraper
  labels:
    {{- include "trade.labels" . | nindent 4 }}
    component: tvscraper
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "trade.selectorLabels" . | nindent 6 }}
      component: tvscraper
  template:
    metadata:
      labels:
        {{- include "trade.selectorLabels" . | nindent 8 }}
        component: tvscraper
    spec:
      initContainers:
      - name: wait-for-rabbitmq
        image: busybox:1.35
        command: ['sh', '-c']
        args:
          - |
            until nc -z {{ include "trade.fullname" . }}-rabbitmq 5672; do
              echo "Waiting for RabbitMQ..."
              sleep 5
            done
            echo "RabbitMQ is ready!"
      containers:
      - name: tvscraper
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.scrapers.tvscraper.image.repository }}:{{ .Values.scrapers.tvscraper.image.tag }}"
        imagePullPolicy: {{ .Values.scrapers.tvscraper.image.pullPolicy }}
        command: ["sh", "-c"]
        args:
          - |
            Xvfb :99 -screen 0 1280x1024x24 -nolisten tcp &
            export DISPLAY=:99
            python -m news_scraper.scraper_trading_view
        env:
        - name: DISPLAY
          value: {{ .Values.scrapers.tvscraper.env.DISPLAY | quote }}
        - name: SELENIUM_HUB_URL
          value: {{ include "trade.seleniumHubURL" . | quote }}
        - name: TRADE_VIEW_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "trade.fullname" . }}-tvscraper-secret
              key: TRADE_VIEW_USER
        - name: TRADE_VIEW_PASS
          valueFrom:
            secretKeyRef:
              name: {{ include "trade.fullname" . }}-tvscraper-secret
              key: TRADE_VIEW_PASS
        - name: RABBITMQ_HOST
          value: {{ include "trade.rabbitmqHost" . | quote }}
        - name: RABBITMQ_USER
          value: {{ .Values.scrapers.tvscraper.mqUser | quote }}
        - name: RABBITMQ_PASS
          value: {{ .Values.scrapers.tvscraper.mqPass | quote }}
        volumeMounts:
          {{- if .Values.persistence.output.enabled }}
          - name: output-volume
            mountPath: /app/output
          {{- end }}
        resources:
          {{- toYaml .Values.scrapers.tvscraper.resources | nindent 10 }}
      {{- if .Values.persistence.output.enabled }}
      volumes:
      - name: output-volume
        persistentVolumeClaim:
          claimName: {{ include "trade.fullname" . }}-output-pvc
      {{- end }}
{{- end }}