# 最简单的有效配置
trigger:
  branches:
    include:
      - main

# 关键修改：使用显式池声明并跳过系统任务
pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'
  demands: []  # 跳过系统任务

steps:
- checkout: self  # 检出代码
  
- script: |
    echo "✅ 成功运行最简单的流水线!"
    echo "Build ID: $(Build.BuildId)"
    echo "Agent name: $(Agent.Name)"
  displayName: '验证执行'