# 添加资源限制和显式作业控制
resources: 
  containers: [] 
  repositories: []

trigger:
  branches:
    include:
      - main

jobs:
- job: Ensure_Single_Job
  displayName: "Single Job Execution"
  pool:
    vmImage: 'ubuntu-latest'
    demands:  # 添加资源需求
    - agent.name -equals $(agent.name)
  
  variables:
    IMAGE_TAG: "$(Build.BuildId)"
  
  steps:
    - checkout: self
    
    - script: |
        echo "✅ 独占作业槽位成功"
        echo "当前代理: $(agent.name)"
      displayName: "槽位验证"
    
    - script: |
        echo "代码检出完成"
        ls -al
      displayName: "文件列表检查"
    
    - script: |
        echo "检查系统依赖..."
        docker --version
        docker compose version
      displayName: "依赖检查"
    
    - script: |
        echo "运行测试..."
        echo "✅ 所有测试通过!"
      displayName: "执行测试"
    
    - script: |
        echo "构建Docker镜像 (Tag: $IMAGE_TAG)..."
        cd docker
        docker compose build
      displayName: "构建Docker镜像"