trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_TAG: "$(Build.BuildId)"

steps:
  - checkout: self

  - script: |
      echo "Code checked out from GitHub"
      ls -al
    displayName: "List files"

  - task: Bash@3
    displayName: 'Run tests'
    inputs:
      targetType: inline
      script: |
        echo "Running tests..."
        docker --version
        echo "✅ Tests passed!"
