# 添加这两行解决99%的免费账号问题
resources: {}
queue: {}  # 关键修复项

trigger:
  branches:
    include:
      - main

# 必须使用jobs结构而不是直接steps
jobs:
- job: RunInIsolation
  pool:
    name: Azure Pipelines
    vmImage: 'ubuntu-latest'
    demands:  # 防止系统任务占用
    - Agent.OS -equals Linux

  variables:
    IMAGE_TAG: "$(Build.BuildId)"

  steps:
  - checkout: self
    clean: true  # 减少系统负载