{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "trade.fullname" . }}-network-policy
  labels:
    {{- include "trade.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "trade.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "trade.selectorLabels" . | nindent 10 }}
    {{- if .Values.networkPolicy.allowedNamespaces }}
    {{- range .Values.networkPolicy.allowedNamespaces }}
    - namespaceSelector:
        matchLabels:
          name: {{ . }}
    {{- end }}
    {{- end }}
  egress:
  - {} # Allow all egress traffic
{{- end }}
