FROM python:3.12-slim

# Install dependencies
RUN pip install --no-cache-dir --upgrade p
RUN pip install --no-cache-dir pika aio_pika requests beautifulsoup4 lxml openai cachetools selenium
RUN pip install --no-cache-dir grpcio grpcio-tools
RUN pip install --no-cache-dir langchain langchain-openai langchain-core langgraph langchain-community

RUN useradd -m -u 1000 appuser

# Copy the Python script into the container
COPY common /app/common
COPY news_analyser /app/news_analyser
COPY news_model /app/news_model
COPY proto /app/proto
RUN chown -R appuser:appuser /app

# Switch to the user
USER appuser
ENV HOME=/app
WORKDIR /app

# Set environment variable to prevent Python from writing pyc files
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH=/app/proto:/app/news_scraper:/app/news_analyser:/app/news_model

# Environment variable expected: DEEPSEEK_API_KEY
CMD ["tail", "-f", "/dev/null"]