# Use official Python base image
FROM python:3.11-slim

# Set work directory inside container
WORKDIR /app

# Install system dependencies (for pip and security)
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir \
    weaviate-client \
    pika \
    pytest \
    aio_pika \
    pytest-asyncio \
    pytest-mock \
    pytest-cov \
    pytest-xdist \
    psycopg2-binary \
    asyncpg \
    sentence-transformers

RUN apt-get update && apt-get install -y iputils-ping && rm -rf /var/lib/apt/lists/*

RUN useradd -m -u 1000 appuser

RUN chown -R appuser:appuser /app

# Switch to the user
USER appuser
ENV HOME=/app
WORKDIR /app

# Set environment variable to prevent Python from writing pyc files
ENV PYTHONUNBUFFERED 1
# ENV PYTHONPATH=/app/proto:/app/news_scraper:/app/news_model:/app/common:/app/news_ingestor:/app/news_ingestor:/app/news_model:/app/common:/app/news_ingestor

# Set default command
CMD ["tail", "-f", "/dev/null"]
