FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir grpcio grpcio-tools yfinance pandas

# Project root context
COPY stock_hub/ /app/stock_hub/
COPY proto/ /app/proto/

ENV PYTHONPATH=/app/stock_hub:/app/proto

CMD ["python", "-m", "stock_hub.quote"]
