services:
  unittest:
    build:
      context: .
      dockerfile: Dockerfile.python.test
    container_name: trade_test
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - PIP_NO_CACHE_DIR=1
    # avoid test files to share the global singleton instance
    command: pytest -v 

