version: "3.8"
services:
  scraper:
    build:
      context: ../  # Set build context to project root
      dockerfile: docker/Dockerfile.iv
    container_name: python-scraper-iv
    volumes:
      - ../output:/app/output  # Mount the current directory to /app in the container
    environment:
      - DISPLAY=:99  # If running headlessly or using Xvfb
    ports:
      - "5000:5000"  # Example port forwarding (if needed)
    networks:
      - scraper-network
    restart: always  # Restart container if it crashes

networks:
  scraper-network:
    driver: bridge
