FROM python:3.9-slim

# Install dependencies
RUN pip install --no-cache-dir --upgrade p
RUN pip install pika aio_pika requests beautifulsoup4 lxml openai
RUN pip install --no-cache-dir grpcio grpcio-tools

RUN useradd -m -u 1000 appuser

# Copy the Python script into the container
COPY news_scraper /app/news_scraper
COPY proto /app/proto
RUN chown -R appuser:appuser /app

# Switch to the user
USER appuser
ENV HOME=/app
WORKDIR /app

# Set environment variable to prevent Python from writing pyc files
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH=/app/proto:/app/news_scraper

# Environment variable expected: DEEPSEEK_API_KEY
CMD ["tail", "-f", "/dev/null"]