apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trade-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    path: helm
    repoURL: https://github.com/wayming/trade.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      releaseName: trade
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true