# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analysis_push_gateway.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61nalysis_push_gateway.proto\x12\x0c\x61nalysispush\"\x1e\n\x0bPushRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\":\n\x0cPushResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x15\n\rresponse_text\x18\x02 \x01(\t2T\n\x13\x41nalysisPushGateway\x12=\n\x04Push\x12\x19.analysispush.PushRequest\x1a\x1a.analysispush.PushResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis_push_gateway_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PUSHREQUEST']._serialized_start=45
  _globals['_PUSHREQUEST']._serialized_end=75
  _globals['_PUSHRESPONSE']._serialized_start=77
  _globals['_PUSHRESPONSE']._serialized_end=135
  _globals['_ANALYSISPUSHGATEWAY']._serialized_start=137
  _globals['_ANALYSISPUSHGATEWAY']._serialized_end=221
# @@protoc_insertion_point(module_scope)
