# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock_hub.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstock_hub.proto\x12\tstock_hub\"\x1e\n\x0cQuoteRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"N\n\rQuoteResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\t2K\n\nStockQuote\x12=\n\x08GetQuote\x12\x17.stock_hub.QuoteRequest\x1a\x18.stock_hub.QuoteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_hub_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUOTEREQUEST']._serialized_start=30
  _globals['_QUOTEREQUEST']._serialized_end=60
  _globals['_QUOTERESPONSE']._serialized_start=62
  _globals['_QUOTERESPONSE']._serialized_end=140
  _globals['_STOCKQUOTE']._serialized_start=142
  _globals['_STOCKQUOTE']._serialized_end=217
# @@protoc_insertion_point(module_scope)
