# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import trade_executor_pb2 as trade__executor__pb2


class TradeExecutorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTrade = channel.unary_unary(
                '/trading.TradeExecutor/ExecuteTrade',
                request_serializer=trade__executor__pb2.TradeRequest.SerializeToString,
                response_deserializer=trade__executor__pb2.TradeResponse.FromString,
                )


class TradeExecutorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteTrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradeExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTrade,
                    request_deserializer=trade__executor__pb2.TradeRequest.FromString,
                    response_serializer=trade__executor__pb2.TradeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trading.TradeExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TradeExecutor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trading.TradeExecutor/ExecuteTrade',
            trade__executor__pb2.TradeRequest.SerializeToString,
            trade__executor__pb2.TradeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
