# Default values for trade.
# This is a YAML-formatted file.
# Declare variables to be substituted into your templates.

global:
  imageRegistry: ghcr.io/wayming/trade
  imagePullSecrets: []
  storageClass: ""
  rabbitmqUser: admin
  rabbitmqPass: password
  deepseekApiKey: ""
# Network Policy
networkPolicy:
  enabled: true
  allowedNamespaces: []
# Persistent Volumes
persistence:
  output:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteMany
    storageClass: ""
  rabbitmq:
    enabled: true
    size: 5Gi
    accessMode: ReadWriteOnce
    storageClass: ""
  weaviate:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce
    storageClass: ""
# RabbitMQ Configuration
rabbitmq:
  enabled: true
  image:
    repository: rabbitmq
    tag: "latest"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5672
    managementPort: 15672
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  env:
    # Use default guest/guest, do not create new user
    RABBITMQ_DEFAULT_USER: "admin"
    RABBITMQ_DEFAULT_PASS: "password"
# Weaviate Configuration
weaviate:
  enabled: true
  image:
    repository: semitechnologies/weaviate
    tag: "1.21.2"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
    grpcPort: 50051
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  env:
    QUERY_DEFAULTS_LIMIT: "25"
    AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
    PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
# Scrapers Configuration
scrapers:
  ivscraper:
    enabled: true
    image:
      repository: "ivscraper"
      tag: "1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e"
      pullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    env:
      DISPLAY: ":99"
  tvscraper:
    enabled: true
    tradeViewUser: ""
    tradeViewPass: ""
    mqUser: "{{ .Values.rabbitmqUser }}"
    mqPass: "{{ .Values.rabbitmqPass }}"
    image:
      repository: "tvscraper"
      tag: "1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e"
      pullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    env:
      DISPLAY: ":99"
  ivanalyser:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
  tvanalyser:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
  mock_executor:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
  stock_hub:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
  aws_gateway:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
  news_store:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
# analysers Configuration
analysers:
  ivanalyser:
    enabled: true
    image:
      repository: "ivanalyser"
      tag: "1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e"
      pullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
  tvanalyser:
    enabled: true
    image:
      repository: "tvanalyser"
      tag: "1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e"
      pullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
  ivscraper:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
  tvscraper:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
  mock_executor:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
  stock_hub:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
  aws_gateway:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
  news_store:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
# Core Services Configuration
coreServices:
  mockExecutor:
    enabled: true
    image:
      repository: "mock_executor"
      tag: "latest"
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 50051
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  stockHub:
    enabled: true
    image:
      repository: "stock_hub"
      tag: "latest"
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 50052
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  awsGateway:
    enabled: true
    image:
      repository: "aws_gateway"
      tag: "latest"
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 50053
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  newsStore:
    enabled: true
    image:
      repository: "news_store"
      tag: "latest"
      pullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  ivscraper:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
  tvscraper:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
  ivanalyser:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
  tvanalyser:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
  mock_executor:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
  stock_hub:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
  aws_gateway:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
  news_store:
    image:
      tag: 1c2f5a4e0969516c4ec5e20636556bfaeaf5c44e
# Init Containers
initContainers:
  dependencyChecks:
    enabled: true
    image:
      repository: busybox
      tag: "1.35"
      pullPolicy: Always
selenium:
  hub:
    image: selenium/hub:4.35.0
    replicas: 1
    resources: {}
    serviceName: selenium-hub
    service:
      port: 4444
      env:
        VNC_PASSWORD: "secret"
  nodeChrome:
    image: selenium/node-chrome:4.35.0
    replicas: 2
    shmSize: 2Gi
    resources: {}
