name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # List files
      - name: List files
        run: |
          echo "Code checked out from GitHub"
          ls -al

      # Build images
      - name: Build images
        run: docker compose -f docker/docker-compose-ci.yml build 

      # Test
      - name: Run tests
        run: |
          echo "Running tests..."
          echo "✅ Tests passed!"
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout code (required for push job)
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to the container registry
      - name: Login to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push all images using docker compose
      - name: Build and push all images
        run: |
          docker compose -f docker/docker-compose-ci.yml push