name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 列出文件
      - name: List files
        run: |
          echo "Code checked out from GitHub"
          ls -al

      # 安装 Docker（GitHub 自带）
      - name: Check Docker version
        run: docker --version

      # 运行测试（示例）
      - name: Run tests
        run: |
          echo "Running tests..."
          echo "✅ Tests passed!"
