name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # List files
      - name: List files
        run: |
          echo "Code checked out from GitHub"
          ls -al

      # Build images
      - name: Check Docker version
        run: docker compose -f docker/docker-compose.yml build

      # Test
      - name: Run tests
        run: |
          echo "Running tests..."
          echo "✅ Tests passed!"
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Push images
      - name: Login to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          run: docker compose -f docker/docker-compose.yml push

        